# Generated by Django 3.2.6 on 2021-08-08 17:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='comment',
        ),
        migrations.AddField(
            model_name='commit',
            name='patch',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit', to='page.post', verbose_name='포스트'),
        ),
    ]
