# Generated by Django 3.2.6 on 2021-08-02 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20210803_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='page.post', verbose_name='포스트'),
        ),
    ]
