# Generated by Django 3.2.6 on 2021-08-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210809_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fullDescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='shortDescription',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
