# Generated by Django 3.2.6 on 2021-08-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210809_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fullDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='shortDescription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
